export const SYMBOLS = [
  '$',
  '€',
  '£',
  '¥',
  '₴',
  '₽',
  '¢',
  '₣',
  'zł',
  'Kč',
  '₢',
  '₺',
  '₦',
  '₧',
  '₨',
  '₩',
  '₪',
  '₫',
  '฿',
  '₭',
  '៛',
  '₮',
  '₸',
  '₲'
]

export const ANIMATION_TIMING_FUNCTION_ARRAY = [
  'linear',
  'ease',
  'ease-in',
  'ease-out'
]

export const BACKGROUND_ARRAY = []

export const CURRENCIES_AND_COUNTRIES = [
  ['AU', 'AU', 'AUD'],
  ['AT', 'AT', 'EUR'],
  ['AZ', 'AZ', 'AZM'],
  ['A2', 'PT', 'EUR'],
  ['AX', 'AX', 'EUR'],
  ['AL', 'AL', 'EUR'],
  ['DZ', 'DZ', 'DZD'],
  ['AS', 'AS', 'USD'],
  ['AI', 'AI', 'XCD'],
  ['EN', 'GB', 'GBP'],
  ['AO', 'AO', 'AOA'],
  ['AD', 'AD', 'EUR'],
  ['AG', 'AG', 'XCD'],
  ['AR', 'AR', 'ARS'],
  ['AM', 'AM', 'AMD'],
  ['AW', 'AW', 'AWG'],
  ['AF', 'AF', 'USD'],
  ['BS', 'BS', 'BSD'],
  ['BD', 'BD', 'BDT'],
  ['BB', 'BB', 'BBD'],
  ['BH', 'BH', 'BHD'],
  ['BZ', 'BZ', 'BZD'],
  ['BY', 'BY', 'BYR'],
  ['BE', 'BE', 'EUR'],
  ['BJ', 'BJ', 'XOF'],
  ['BM', 'BM', 'BMD'],
  ['BG', 'BG', 'EUR'],
  ['BO', 'BO', 'BOB'],
  ['BA', 'BA', 'BAM'],
  ['BW', 'BW', 'BWP'],
  ['BR', 'BR', 'BRL'],
  ['VG', 'VG', 'USD'],
  ['BN', 'BN', 'BND'],
  ['BF', 'BF', 'XOF'],
  ['BI', 'BI', 'BIF'],
  ['BT', 'BT', 'BTN'],
  ['VU', 'VU', 'VUV'],
  ['HU', 'HU', 'HUF'],
  ['VE', 'VE', 'VEB'],
  ['VR', 'VG', 'USD'],
  ['TL', 'TL', 'USD'],
  ['VN', 'VN', 'VND'],
  ['GA', 'GA', 'XAF'],
  ['GY', 'GY', 'GYD'],
  ['HT', 'HT', 'HTG'],
  ['GM', 'GM', 'GMD'],
  ['GH', 'GH', 'GHS'],
  ['GP', 'GP', 'EUR'],
  ['GT', 'GT', 'GTQ'],
  ['GN', 'GN', 'GNF'],
  ['GW', 'GW', 'XOF'],
  ['DE', 'DE', 'EUR'],
  ['GG', 'GG', 'GBP'],
  ['GI', 'GI', 'GIP'],
  ['HO', 'NL', 'EUR'],
  ['HN', 'HN', 'HNL'],
  ['HK', 'HK', 'HKD'],
  ['VA', 'VA', 'EUR'],
  ['GD', 'GD', 'XCD'],
  ['GL', 'GL', 'DKK'],
  ['GR', 'GR', 'EUR'],
  ['GE', 'GE', 'GEL'],
  ['GU', 'GU', 'USD'],
  ['DK', 'DK', 'DKK'],
  ['CD', 'CD', 'CDF'],
  ['JE', 'JE', 'GBP'],
  ['DJ', 'DJ', 'DJF'],
  ['DM', 'DM', 'XCD'],
  ['DO', 'DO', 'DOP'],
  ['EP', 'EP', 'EUR'],
  ['EG', 'EG', 'EGP'],
  ['ZM', 'ZM', 'ZMK'],
  ['ZW', 'ZW', 'ZWD'],
  ['YE', 'YE', 'YER'],
  ['IL', 'IL', 'ILS'],
  ['IN', 'IN', 'INR'],
  ['ID', 'ID', 'IDR'],
  ['JO', 'JO', 'JOD'],
  ['IQ', 'IQ', 'NID'],
  ['IE', 'IE', 'EUR'],
  ['IS', 'IS', 'ISK'],
  ['ES', 'ES', 'EUR'],
  ['IT', 'IT', 'EUR'],
  ['KZ', 'KZ', 'KZT'],
  ['KY', 'KY', 'KYD'],
  ['KH', 'KH', 'KHR'],
  ['CM', 'CM', 'XAF'],
  ['CA', 'CA', 'CAD'],
  ['IC', 'ES', 'EUR'],
  ['QA', 'QA', 'QAR'],
  ['KE', 'KE', 'KES'],
  ['CY', 'CY', 'EUR'],
  ['KG', 'KG', 'KGS'],
  ['KI', 'KI', 'AUD'],
  ['CN', 'CN', 'RMB'],
  ['CO', 'CO', 'COP'],
  ['KM', 'KM', 'USD'],
  ['CG', 'CG', 'XAF'],
  ['KV', 'KV', 'EUR'],
  ['KO', 'FM', 'USD'],
  ['CR', 'CR', 'CRC'],
  ['CI', 'CI', 'XOF'],
  ['CU', 'CU', 'CU'],
  ['KW', 'KW', 'KWD'],
  ['CW', 'CW', 'USD'],
  ['LA', 'LA', 'LAK'],
  ['LV', 'LV', 'EUR'],
  ['LS', 'LS', 'LSL'],
  ['LR', 'LR', 'LRD'],
  ['LB', 'LB', 'LBP'],
  ['LY', 'LY', 'LYD'],
  ['LT', 'LT', 'EUR'],
  ['LI', 'LI', 'CHF'],
  ['LU', 'LU', 'EUR'],
  ['MU', 'MU', 'MUR'],
  ['MR', 'MR', 'MRO'],
  ['MG', 'MG', 'MGA'],
  ['M3', 'PT', 'EUR'],
  ['YT', 'YT', 'EUR'],
  ['MO', 'MO', 'MOP'],
  ['MK', 'MK', 'EUR'],
  ['MW', 'MW', 'MWK'],
  ['MY', 'MY', 'MYR'],
  ['ML', 'ML', 'XOF'],
  ['MV', 'MV', 'MVR'],
  ['MT', 'MT', 'EUR'],
  ['MA', 'MA', 'MAD'],
  ['MQ', 'MQ', 'EUR'],
  ['MH', 'MH', 'USD'],
  ['MX', 'MX', 'MXN'],
  ['XL', 'XL', 'EUR'],
  ['MZ', 'MZ', 'MZM'],
  ['MD', 'MD', 'MDL'],
  ['MC', 'MC', 'EUR'],
  ['MN', 'MN', 'MNT'],
  ['MS', 'MS', 'XCD'],
  ['NA', 'NA', 'NAD'],
  ['NP', 'NP', 'NPR'],
  ['NE', 'NE', 'XOF'],
  ['NG', 'NG', 'NGN'],
  ['NL', 'NL', 'EUR'],
  ['NI', 'NI', 'NIO'],
  ['NZ', 'NZ', 'NZD'],
  ['NC', 'NC', 'XPF'],
  ['NO', 'NO', 'NOK'],
  ['BQ', 'BQ', 'USD'],
  ['AE', 'AE', 'AED'],
  ['BL', 'BL', 'EUR'],
  ['E2', 'BQ', 'ANG'],
  ['C3', 'VI', 'USD'],
  ['WF', 'WF', 'XPF'],
  ['OM', 'OM', 'OMR'],
  ['NF', 'NF', 'AUD'],
  ['CV', 'CV', 'CVE'],
  ['CK', 'CK', 'NZD'],
  ['UI', 'VC', 'XCD'],
  ['PK', 'PK', 'PKR'],
  ['PW', 'PW', 'USD'],
  ['PA', 'PA', 'PAB'],
  ['PG', 'PG', 'PGK'],
  ['PY', 'PY', 'PYG'],
  ['PE', 'PE', 'PEN'],
  ['PL', 'PL', 'PLN'],
  ['PO', 'FM', 'USD'],
  ['PT', 'PT', 'EUR'],
  ['PR', 'PR', 'USD'],
  ['RE', 'RE', 'EUR'],
  ['RU', 'RU', 'RUB'],
  ['RT', 'MP', 'USD'],
  ['RW', 'RW', 'RWF'],
  ['RO', 'RO', 'ROL'],
  ['S1', 'BQ', 'ANG'],
  ['SP', 'MP', 'USD'],
  ['WS', 'WS', 'WST'],
  ['SM', 'SM', 'EUR'],
  ['ST', 'ST', 'STD'],
  ['SA', 'SA', 'SAR'],
  ['SZ', 'SZ', 'SZL'],
  ['NB', 'GB', 'GBP'],
  ['MP', 'MP', 'USD'],
  ['SC', 'SC', 'SCR'],
  ['SN', 'SN', 'XOF'],
  ['VC', 'VC', 'XCD'],
  ['UV', 'VI', 'USD'],
  ['KN', 'KN', 'XCD'],
  ['SW', 'KN', 'XCD'],
  ['LC', 'LC', 'XCD'],
  ['SX', 'SX', 'USD'],
  ['VL', 'VI', 'USD'],
  ['RS', 'RS', 'EUR'],
  ['XC', 'XC', 'EUR'],
  ['SG', 'SG', 'SGD'],
  ['SK', 'SK', 'EUR'],
  ['SI', 'SI', 'EUR'],
  ['GB', 'GB', 'GBP'],
  ['US', 'US', 'USD'],
  ['SB', 'SB', 'SBD'],
  ['SR', 'SR', 'SRG'],
  ['VI', 'VI', 'USD'],
  ['SL', 'SL', 'SLL'],
  ['TJ', 'TJ', 'TJS'],
  ['TW', 'TW', 'TWD'],
  ['TH', 'TH', 'THB'],
  ['TA', 'PF', 'XPF'],
  ['TZ', 'TZ', 'TZS'],
  ['TC', 'TC', 'USD'],
  ['TI', 'MP', 'USD'],
  ['TG', 'TG', 'XOF'],
  ['TO', 'TO', 'TOP'],
  ['ZZ', 'VG', 'USD'],
  ['TT', 'TT', 'TTD'],
  ['TU', 'FM', 'USD'],
  ['TV', 'TV', 'AUD'],
  ['TN', 'TN', 'TND'],
  ['TM', 'TM', 'TMT'],
  ['TR', 'TR', 'TRY'],
  ['UG', 'UG', 'UGX'],
  ['UZ', 'UZ', 'UZS'],
  ['UA', 'UA', 'UAH'],
  ['UY', 'UY', 'UYU'],
  ['WL', 'GB', 'GBP'],
  ['FO', 'FO', 'DKK'],
  ['FM', 'FM', 'USD'],
  ['FJ', 'FJ', 'FJD'],
  ['PH', 'PH', 'PHP'],
  ['FI', 'FI', 'EUR'],
  ['FR', 'FR', 'EUR'],
  ['GF', 'GF', 'EUR'],
  ['PF', 'PF', 'XPF'],
  ['HR', 'HR', 'EUR'],
  ['CF', 'CF', 'XAF'],
  ['TD', 'TD', 'XAF'],
  ['ME', 'ME', 'EUR'],
  ['CZ', 'CZ', 'CZK'],
  ['CL', 'CL', 'CLP'],
  ['CH', 'CH', 'CHF'],
  ['SE', 'SE', 'SEK'],
  ['SF', 'GB', 'GBP'],
  ['LK', 'LK', 'LKR'],
  ['EC', 'EC', 'USD'],
  ['GQ', 'GQ', 'XAF'],
  ['SV', 'SV', 'USD'],
  ['ER', 'ER', 'ERN'],
  ['EE', 'EE', 'EUR'],
  ['ET', 'ET', 'ETB'],
  ['ZA', 'ZA', 'ZAR'],
  ['KR', 'KR', 'KRW'],
  ['JM', 'JM', 'JMD'],
  ['YA', 'FM', 'USD'],
  ['JP', 'JP', 'JPY']
]
